// NPR / Public Radio stations with verified direct MP3 streams
// Sourced from radio-browser.info, ordered by state
export const NPR_STATIONS = [
  { state: 'AK', city: 'Bethel',        name: 'KYUK Public Radio',         url: 'https://23023.live.streamtheworld.com/KYUKAM_SC' },
  { state: 'AK', city: 'Kenai',         name: 'KDLL 91.9',                 url: 'http://peridot.streamguys.com:5460/live' },
  { state: 'AK', city: 'Ketchikan',     name: 'KCAW Raven Radio',          url: 'https://tektite.streamguys1.com:5195/live' },
  { state: 'AK', city: 'Kotzebue',      name: 'KOTZ 720',                  url: 'http://14993.live.streamtheworld.com:3690/KOTZAM_SC' },
  { state: 'AK', city: 'McGrath',       name: 'KSKO 89.5',                 url: 'https://ksko.streamguys1.com/live' },
  { state: 'AK', city: 'Sitka',         name: 'KCAW 104.7 Raven Radio',    url: 'https://tektite.streamguys1.com:5195/live' },
  { state: 'AK', city: 'Talkeetna',     name: 'KTNA 88.9',                 url: 'https://ktna.broadcasttool.stream/play' },
  { state: 'AL', city: 'Birmingham',    name: 'WBHM 90.3',                 url: 'https://audio.wbhm.org/live.mp3' },
  { state: 'AL', city: 'Troy',          name: 'WTSU 89.9 Troy Public Radio',url: 'http://live.str3am.com:2380/troy1' },
  { state: 'AL', city: 'Tuscaloosa',    name: 'WUAL 91.5 Alabama Public Radio', url: 'http://15123.live.streamtheworld.com/WUAL_HD1_SC' },
  { state: 'AR', city: 'Fayetteville',  name: 'KUAF 91.3',                 url: 'https://war.streamguys1.com:7031/kuaf1' },
  { state: 'AR', city: 'Little Rock',   name: 'KUAR 89.1',                 url: 'http://26293.live.streamtheworld.com:3690/KUARFM_SC' },
  { state: 'AZ', city: 'Yuma',          name: 'KAWC Arizona Community',    url: 'http://18443.live.streamtheworld.com/KAWCAM_SC' },
  { state: 'CA', city: 'Fresno',        name: 'KVPR 89.3 Valley Public',   url: 'http://27033.live.streamtheworld.com/KVPRFM_SC' },
  { state: 'CA', city: 'Thousand Oaks', name: 'KCLU 88.3',                 url: 'http://kclustream.callutheran.edu:8092/kclump3' },
  { state: 'CO', city: 'Cortez',        name: 'KSJD 91.5',                 url: 'http://war.str3am.com:8430/' },
  { state: 'CO', city: 'Crested Butte', name: 'KBUT 90.3',                 url: 'http://26443.live.streamtheworld.com/KBUTFM_SC' },
  { state: 'DE', city: 'Dover',         name: 'WDDE 91.1',                 url: 'http://26223.live.streamtheworld.com/WDDEFM_SC' },
  { state: 'FL', city: 'Fort Myers',    name: 'WGCU 90.1',                 url: 'http://22213.live.streamtheworld.com:3690/WGCUFM_SC' },
  { state: 'FL', city: 'Jacksonville',  name: 'WJCT 89.9',                 url: 'http://26223.live.streamtheworld.com/WJCTFM_SC' },
  { state: 'GA', city: 'Atlanta',       name: 'WABE 90.1',                 url: 'https://18103.live.streamtheworld.com/WABEFM_HD1.mp3' },
  { state: 'IA', city: 'Sioux City',    name: 'Siouxland Public Radio',    url: 'http://22063.live.streamtheworld.com/KWITFM_SC' },
  { state: 'IA', city: 'Des Moines',    name: 'Iowa Public Radio',         url: 'http://studioone-stream.iowapublicradio.org/StudioOneLow.mp3' },
  { state: 'ID', city: 'Pocatello',     name: 'KISU 91.1',                 url: 'http://kisufm.isu.edu:8000/kisufm' },
  { state: 'IL', city: 'Chicago',       name: 'WBEZ 91.5',                 url: 'http://stream.wbez.org/wbez128.mp3' },
  { state: 'IL', city: 'Macomb',        name: 'WIUM Tri States Public',    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/WIUMFM.mp3' },
  { state: 'KS', city: 'Wichita',       name: 'KMUW 89.1',                 url: 'http://kmuw.streamguys1.com/live' },
  { state: 'KS', city: 'Liberal',       name: 'High Plains Public Radio',  url: 'http://14843.live.streamtheworld.com/KANZFM_HPPR_SC' },
  { state: 'LA', city: 'Baton Rouge',   name: 'WRKF 89.3',                 url: 'http://22213.live.streamtheworld.com/WRKFFM_SC' },
  { state: 'MA', city: 'Boston',        name: 'GBH 89.7',                  url: 'https://wgbh-live.streamguys1.com/wgbh-noads' },
  { state: 'MA', city: 'Nationwide',    name: 'NPR News Stream',           url: 'https://npr-ice.streamguys1.com/live.mp3' },
  { state: 'MD', city: 'Princess Anne', name: 'WESM 91.3',                 url: 'http://18123.live.streamtheworld.com/WESMFM_SC' },
  { state: 'MD', city: 'Salisbury',     name: 'WSCL 89.5 Delmarva',       url: 'http://26223.live.streamtheworld.com/WSCLFM_SC' },
  { state: 'ME', city: 'Portland',      name: 'Maine Public Radio',        url: 'http://22213.live.streamtheworld.com/WMEA_CLASSICAL_SC' },
  { state: 'MI', city: 'Detroit',       name: 'WEMU 89.1',                 url: 'http://22203.live.streamtheworld.com/WEMUFM_SC' },
  { state: 'MI', city: 'Mount Pleasant',name: 'WCMU 89.5',                 url: 'http://22213.live.streamtheworld.com/WCMUFM_SC' },
  { state: 'MI', city: 'Marquette',     name: 'Public Radio 90',           url: 'https://wnmu.streamguys1.com/wnmu-fm' },
  { state: 'MO', city: 'Cape Girardeau',name: 'KRCU 90.9',                 url: 'http://krculive.semo.edu:8000/128k' },
  { state: 'MO', city: 'Maryville',     name: 'KXCV 90.5 NW Missouri',    url: 'http://198.209.246.63:8000/' },
  { state: 'MO', city: 'Springfield',   name: 'KSMU Ozarks Public Radio',  url: 'http://ksmu.streamguys1.com/ksmu4' },
  { state: 'MT', city: 'Billings',      name: 'KEMC 91.7 Yellowstone PR',  url: 'http://ypr-sc.streamguys.net/live' },
  { state: 'MT', city: 'Missoula',      name: 'Montana Public Radio',      url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/KUFMFM.mp3' },
  { state: 'ND', city: 'Fargo',         name: 'Prairie Public Radio',      url: 'http://18853.live.streamtheworld.com/KCNDHD3_SC' },
  { state: 'NE', city: 'Omaha',         name: 'NET Nebraska',              url: 'https://npr-ice.streamguys1.com/live.mp3' },
  { state: 'NM', city: 'Albuquerque',   name: 'KANW 89.1',                 url: 'http://27163.live.streamtheworld.com/KANWFM_SC' },
  { state: 'NV', city: 'Reno',          name: 'KUNR 88.7',                 url: 'https://kunrstream.com:8443/live' },
  { state: 'NY', city: 'Rochester',     name: 'WRUR 88.5',                 url: 'http://playerservices.streamtheworld.com/api/livestream-redirect/WRURFM.mp3' },
  { state: 'NY', city: 'Syracuse',      name: 'WAER 88.3',                 url: 'http://26223.live.streamtheworld.com/WAERFM_SC' },
  { state: 'NY', city: 'Watertown',     name: 'NCPR North Country PR',     url: 'https://ncpr-ice.streamguys1.com/ncpr-96k.mp3' },
  { state: 'OH', city: 'Athens',        name: 'WOUB 91.3',                 url: 'http://26423.live.streamtheworld.com:3690/WOUBFM_SC' },
  { state: 'OH', city: 'Toledo',        name: 'WGTE 91.3',                 url: 'http://22063.live.streamtheworld.com:3690/WGTEFM_SC' },
  { state: 'OK', city: 'Lawton',        name: 'KCCU 89.3',                 url: 'http://22063.live.streamtheworld.com:3690/KCCUFM_SC' },
  { state: 'OK', city: 'Norman',        name: 'KGOU 106.3',                url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/KGOUFM_64.mp3' },
  { state: 'OK', city: 'Stillwater',    name: 'KOSU 91.7',                 url: 'http://18123.live.streamtheworld.com:3690/KOSUFM_NEWS_SC' },
  { state: 'OR', city: 'Ashland',       name: 'KSOR 90.1 Jefferson PR',    url: 'http://jpr.streamguys.org/jpr-news' },
  { state: 'PA', city: 'Philadelphia',  name: 'WHYY 90.9',                 url: 'https://ais-sa3.cdnstream1.com/2556_128.mp3' },
  { state: 'PA', city: 'Scranton',      name: 'WVIA HD2',                  url: 'http://19473.live.streamtheworld.com/WVIAHD2_SC' },
  { state: 'RI', city: 'Providence',    name: 'RIPR The Public\'s Radio',  url: 'https://amber.streamguys1.com:5595/riprdeskweb' },
  { state: 'TN', city: 'Chattanooga',   name: 'WUTC 88.1',                 url: 'http://26423.live.streamtheworld.com/WUTCFM_SC' },
  { state: 'TN', city: 'Memphis',       name: 'WKNO 91.1',                 url: 'http://26223.live.streamtheworld.com/WKNOFM_SC' },
  { state: 'TX', city: 'Abilene',       name: 'KACU 89.5',                 url: 'http://22983.live.streamtheworld.com/KACUFM_SC' },
  { state: 'TX', city: 'Austin',        name: 'KUT 90.5',                  url: 'https://streams.kut.org/4426_128.mp3' },
  { state: 'TX', city: 'Marfa',         name: 'KRTS 93.5 Marfa PR',        url: 'http://marfapr-ice.streamguys1.com/krts' },
  { state: 'TX', city: 'Beaumont',      name: 'KVLU 91.3',                 url: 'http://kvlustream.lamar.edu:8000/stream' },
  { state: 'TX', city: 'Texarkana',     name: 'KTXK 91.5',                 url: 'http://ktxkweb.texarkanacollege.edu:8000/;' },
  { state: 'UT', city: 'Logan',         name: 'KUSU 91.5',                 url: 'http://uprxstreamer.usu.edu:8000/stream' },
  { state: 'VA', city: 'Lexington',     name: 'WLUR 91.5',                 url: 'http://perseus.shoutca.st:9045/stream' },
  { state: 'VT', city: 'Burlington',    name: 'WVPS 107.9 Vermont PR',     url: 'http://vpr.streamguys.net/vpr64.mp3' },
  { state: 'WA', city: 'Tacoma',        name: 'KNKX 88.5',                 url: 'https://knkx-live-a.edge.audiocdn.com/6284_128k' },
  { state: 'WI', city: 'Madison',       name: 'Wisconsin Public Radio',    url: 'https://wpr-ice.streamguys1.com/wpr-music-mp3-96' },
  { state: 'WI', city: 'Rhinelander',   name: 'WXPR 91.7',                 url: 'http://amber.streamguys.com:4370/wxpr2' },
  { state: 'WV', city: 'Morgantown',    name: 'WVPG West Virginia PR',     url: 'http://live.str3am.com:7820/wvpublic.mp3' },
  { state: 'WY', city: 'Laramie',       name: 'Wyoming Public Radio',      url: 'https://npr-ice.streamguys1.com/live.mp3' },
];

// Find best NPR station for an alert's state
export function nprStationForAlert(alert) {
  const areaDesc = alert?.properties?.areaDesc || '';
  const states = [...new Set((areaDesc.match(/\b([A-Z]{2})\b/g) || []))];
  return NPR_STATIONS.find(s => states.includes(s.state)) || null;
}
